# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designs/change_object_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 445)
        Form.setMinimumSize(QtCore.QSize(600, 0))
        Form.setStyleSheet("QWidget {\n"
"    background-color: #333345;\n"
"}\n"
"\n"
"QColorDialog QLabel {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QColorDialog QSpinBox {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QColorDialog QLineEdit {\n"
"    color: white;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QColorDialog {\n"
"    background-color: #333345;\n"
"    color: white;\n"
"}\n"
"\n"
"QColorDialog QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white; \n"
"    font-size: 16px\n"
"}\n"
"\n"
"QColorDialog QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.filler_color_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.filler_color_label.setFont(font)
        self.filler_color_label.setStyleSheet("color: white;")
        self.filler_color_label.setObjectName("filler_color_label")
        self.horizontalLayout_6.addWidget(self.filler_color_label)
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.filler_color = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filler_color.sizePolicy().hasHeightForWidth())
        self.filler_color.setSizePolicy(sizePolicy)
        self.filler_color.setMinimumSize(QtCore.QSize(70, 0))
        self.filler_color.setStyleSheet("background-color: white;")
        self.filler_color.setText("")
        self.filler_color.setObjectName("filler_color")
        self.horizontalLayout_6.addWidget(self.filler_color)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_6, 11, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 13, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem4, 10, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.name_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_label.setFont(font)
        self.name_label.setStyleSheet("color: white;")
        self.name_label.setObjectName("name_label")
        self.horizontalLayout_4.addWidget(self.name_label)
        spacerItem6 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setStyleSheet("color: white;")
        self.name.setObjectName("name")
        self.horizontalLayout_4.addWidget(self.name)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.gridLayout.addLayout(self.horizontalLayout_4, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white; ")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem8, 12, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.stroke_width_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stroke_width_label.setFont(font)
        self.stroke_width_label.setStyleSheet("color: white;")
        self.stroke_width_label.setObjectName("stroke_width_label")
        self.horizontalLayout_2.addWidget(self.stroke_width_label)
        spacerItem10 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.stroke_width = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stroke_width.sizePolicy().hasHeightForWidth())
        self.stroke_width.setSizePolicy(sizePolicy)
        self.stroke_width.setStyleSheet("color: white; font-size: 16px;")
        self.stroke_width.setMinimum(1)
        self.stroke_width.setMaximum(15000)
        self.stroke_width.setObjectName("stroke_width")
        self.horizontalLayout_2.addWidget(self.stroke_width)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem12 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.ok = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ok.setFont(font)
        self.ok.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 30px; \n"
"    color: white\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.ok.setObjectName("ok")
        self.horizontalLayout_3.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel.setFont(font)
        self.cancel.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 30px; \n"
"    color: white\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_3.addWidget(self.cancel)
        spacerItem13 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem13)
        self.gridLayout.addLayout(self.horizontalLayout_3, 14, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem14, 4, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.stroke_color_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stroke_color_label.setFont(font)
        self.stroke_color_label.setStyleSheet("color: white;")
        self.stroke_color_label.setObjectName("stroke_color_label")
        self.horizontalLayout_5.addWidget(self.stroke_color_label)
        spacerItem16 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem16)
        self.stroke_color = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stroke_color.sizePolicy().hasHeightForWidth())
        self.stroke_color.setSizePolicy(sizePolicy)
        self.stroke_color.setMinimumSize(QtCore.QSize(70, 0))
        self.stroke_color.setStyleSheet("background-color: white;")
        self.stroke_color.setText("")
        self.stroke_color.setObjectName("stroke_color")
        self.horizontalLayout_5.addWidget(self.stroke_color)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.gridLayout.addLayout(self.horizontalLayout_5, 9, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem18, 8, 1, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem19, 6, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.filler_color_label.setText(_translate("Form", "Цвет заливки      "))
        self.name_label.setText(_translate("Form", "Имя        "))
        self.label_4.setText(_translate("Form", "Свойства объекта"))
        self.stroke_width_label.setText(_translate("Form", "Ширина обводки"))
        self.ok.setText(_translate("Form", "Сохранить"))
        self.cancel.setText(_translate("Form", "Отмена"))
        self.stroke_color_label.setText(_translate("Form", "Цвет обводки     "))
