# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designs/project_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 768)
        MainWindow.setStyleSheet("* {\n"
"    background-color: #333345;\n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.first_frame = QtWidgets.QPushButton(self.centralwidget)
        self.first_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.first_frame.setObjectName("first_frame")
        self.gridLayout.addWidget(self.first_frame, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 4, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.timeline_visual_multiplier = QtWidgets.QSlider(self.centralwidget)
        self.timeline_visual_multiplier.setMaximumSize(QtCore.QSize(16777215, 16))
        self.timeline_visual_multiplier.setMaximum(200)
        self.timeline_visual_multiplier.setProperty("value", 100)
        self.timeline_visual_multiplier.setOrientation(QtCore.Qt.Horizontal)
        self.timeline_visual_multiplier.setObjectName("timeline_visual_multiplier")
        self.verticalLayout_6.addWidget(self.timeline_visual_multiplier)
        self.timeline_visual_multiplier_description = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeline_visual_multiplier_description.setFont(font)
        self.timeline_visual_multiplier_description.setStyleSheet("color: white;")
        self.timeline_visual_multiplier_description.setAlignment(QtCore.Qt.AlignCenter)
        self.timeline_visual_multiplier_description.setObjectName("timeline_visual_multiplier_description")
        self.verticalLayout_6.addWidget(self.timeline_visual_multiplier_description)
        self.gridLayout.addLayout(self.verticalLayout_6, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.current_frame = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.current_frame.setFont(font)
        self.current_frame.setStyleSheet("color: white; font-size: 16px;")
        self.current_frame.setMaximum(5000)
        self.current_frame.setProperty("value", 600)
        self.current_frame.setObjectName("current_frame")
        self.gridLayout.addWidget(self.current_frame, 2, 3, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(299, 16777215))
        self.widget.setStyleSheet("background-color: #5f5fc3;\n"
"    border-radius: 10px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.move_to_background = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.move_to_background.setFont(font)
        self.move_to_background.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.move_to_background.setObjectName("move_to_background")
        self.verticalLayout_5.addWidget(self.move_to_background)
        self.move_to_overground = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.move_to_overground.setFont(font)
        self.move_to_overground.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.move_to_overground.setObjectName("move_to_overground")
        self.verticalLayout_5.addWidget(self.move_to_overground)
        self.change_object = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.change_object.setFont(font)
        self.change_object.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.change_object.setObjectName("change_object")
        self.verticalLayout_5.addWidget(self.change_object)
        self.delete_object = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_object.setFont(font)
        self.delete_object.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.delete_object.setObjectName("delete_object")
        self.verticalLayout_5.addWidget(self.delete_object)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.objects_area = QtWidgets.QScrollArea(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objects_area.sizePolicy().hasHeightForWidth())
        self.objects_area.setSizePolicy(sizePolicy)
        self.objects_area.setStyleSheet("background-color: #5f5fc3;")
        self.objects_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.objects_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.objects_area.setWidgetResizable(True)
        self.objects_area.setObjectName("objects_area")
        self.objects_area_layout_widget = QtWidgets.QWidget()
        self.objects_area_layout_widget.setGeometry(QtCore.QRect(0, 0, 162, 242))
        self.objects_area_layout_widget.setObjectName("objects_area_layout_widget")
        self.objects_area_layout = QtWidgets.QVBoxLayout(self.objects_area_layout_widget)
        self.objects_area_layout.setObjectName("objects_area_layout")
        self.radioButton = QtWidgets.QRadioButton(self.objects_area_layout_widget)
        self.radioButton.setObjectName("radioButton")
        self.radio_group = QtWidgets.QButtonGroup(MainWindow)
        self.radio_group.setObjectName("radio_group")
        self.radio_group.addButton(self.radioButton)
        self.objects_area_layout.addWidget(self.radioButton)
        self.objects_area.setWidget(self.objects_area_layout_widget)
        self.verticalLayout_2.addWidget(self.objects_area)
        self.gridLayout.addWidget(self.widget, 1, 4, 1, 1)
        self.last_frame = QtWidgets.QPushButton(self.centralwidget)
        self.last_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.last_frame.setObjectName("last_frame")
        self.gridLayout.addWidget(self.last_frame, 5, 4, 1, 1)
        self.delete_frame = QtWidgets.QPushButton(self.centralwidget)
        self.delete_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.delete_frame.setObjectName("delete_frame")
        self.gridLayout.addWidget(self.delete_frame, 0, 4, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(205, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(299, 16777215))
        self.widget_2.setStyleSheet("background-color: #5f5fc3;\n"
"    border-radius: 10px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pencil_tool = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pencil_tool.sizePolicy().hasHeightForWidth())
        self.pencil_tool.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pencil_tool.setFont(font)
        self.pencil_tool.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.pencil_tool.setObjectName("pencil_tool")
        self.verticalLayout_7.addWidget(self.pencil_tool)
        self.line_tool = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_tool.sizePolicy().hasHeightForWidth())
        self.line_tool.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_tool.setFont(font)
        self.line_tool.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.line_tool.setObjectName("line_tool")
        self.verticalLayout_7.addWidget(self.line_tool)
        self.ellipse_tool = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ellipse_tool.sizePolicy().hasHeightForWidth())
        self.ellipse_tool.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ellipse_tool.setFont(font)
        self.ellipse_tool.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.ellipse_tool.setObjectName("ellipse_tool")
        self.verticalLayout_7.addWidget(self.ellipse_tool)
        self.fill_tool = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fill_tool.sizePolicy().hasHeightForWidth())
        self.fill_tool.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fill_tool.setFont(font)
        self.fill_tool.setStyleSheet(".QPushButton {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    border-radius: 10px; \n"
"    padding: 10px; \n"
"    color: white;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"    background-color: #7c7cff;\n"
"}")
        self.fill_tool.setObjectName("fill_tool")
        self.verticalLayout_7.addWidget(self.fill_tool)
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.frame_rate = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.frame_rate.setFont(font)
        self.frame_rate.setStyleSheet("color: white; font-size: 16px;")
        self.frame_rate.setMaximum(5000)
        self.frame_rate.setProperty("value", 144)
        self.frame_rate.setObjectName("frame_rate")
        self.gridLayout.addWidget(self.frame_rate, 2, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 85))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 976, 62))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.timeline = QtWidgets.QSlider(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeline.sizePolicy().hasHeightForWidth())
        self.timeline.setSizePolicy(sizePolicy)
        self.timeline.setMinimumSize(QtCore.QSize(80, 16))
        self.timeline.setMinimum(1)
        self.timeline.setOrientation(QtCore.Qt.Horizontal)
        self.timeline.setObjectName("timeline")
        self.verticalLayout_3.addWidget(self.timeline)
        self.ruler = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ruler.sizePolicy().hasHeightForWidth())
        self.ruler.setSizePolicy(sizePolicy)
        self.ruler.setMinimumSize(QtCore.QSize(0, 16))
        self.ruler.setMaximumSize(QtCore.QSize(50, 20))
        self.ruler.setObjectName("ruler")
        self.verticalLayout_3.addWidget(self.ruler)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 4, 0, 1, 5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.copy_frame = QtWidgets.QPushButton(self.centralwidget)
        self.copy_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.copy_frame.setObjectName("copy_frame")
        self.horizontalLayout_3.addWidget(self.copy_frame)
        self.paste_frame = QtWidgets.QPushButton(self.centralwidget)
        self.paste_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.paste_frame.setObjectName("paste_frame")
        self.horizontalLayout_3.addWidget(self.paste_frame)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.create_frame = QtWidgets.QPushButton(self.centralwidget)
        self.create_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.create_frame.setObjectName("create_frame")
        self.gridLayout.addWidget(self.create_frame, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.previous_frame = QtWidgets.QPushButton(self.centralwidget)
        self.previous_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.previous_frame.setObjectName("previous_frame")
        self.horizontalLayout_2.addWidget(self.previous_frame)
        self.next_frame = QtWidgets.QPushButton(self.centralwidget)
        self.next_frame.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    padding: 2px;\n"
"    border-style: none;\n"
"    border-radius: 0;\n"
"    background-color: #3b3b4b;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #4a4a5d;\n"
"    border-style: none;\n"
"}")
        self.next_frame.setObjectName("next_frame")
        self.horizontalLayout_2.addWidget(self.next_frame)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 2, 1, 1)
        self.drawing_area = QtWidgets.QScrollArea(self.centralwidget)
        self.drawing_area.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.drawing_area.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.drawing_area.setWidgetResizable(True)
        self.drawing_area.setObjectName("drawing_area")
        self.drawing_area_container = QtWidgets.QWidget()
        self.drawing_area_container.setGeometry(QtCore.QRect(0, 0, 1022, 1022))
        self.drawing_area_container.setObjectName("drawing_area_container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.drawing_area_container)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.canvas_placeholder = QtWidgets.QWidget(self.drawing_area_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvas_placeholder.sizePolicy().hasHeightForWidth())
        self.canvas_placeholder.setSizePolicy(sizePolicy)
        self.canvas_placeholder.setMinimumSize(QtCore.QSize(1000, 1000))
        self.canvas_placeholder.setObjectName("canvas_placeholder")
        self.horizontalLayout.addWidget(self.canvas_placeholder)
        self.drawing_area.setWidget(self.drawing_area_container)
        self.gridLayout.addWidget(self.drawing_area, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 30))
        self.menubar.setStyleSheet("* {\n"
"    background-color: #5f5fc3; \n"
"    border-style: none; \n"
"    padding: 2px;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"*:hover {\n"
"    background-color: #5f5fc3; \n"
"}")
        self.menubar.setObjectName("menubar")
        self.file_window = QtWidgets.QMenu(self.menubar)
        self.file_window.setObjectName("file_window")
        self.render_window = QtWidgets.QMenu(self.menubar)
        self.render_window.setObjectName("render_window")
        self.help_window = QtWidgets.QMenu(self.menubar)
        self.help_window.setObjectName("help_window")
        self.canvas_window = QtWidgets.QMenu(self.menubar)
        self.canvas_window.setObjectName("canvas_window")
        MainWindow.setMenuBar(self.menubar)
        self.to_choose_project_window = QtWidgets.QAction(MainWindow)
        self.to_choose_project_window.setObjectName("to_choose_project_window")
        self.render_animation = QtWidgets.QAction(MainWindow)
        self.render_animation.setObjectName("render_animation")
        self.documentation = QtWidgets.QAction(MainWindow)
        self.documentation.setObjectName("documentation")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.render_sequence = QtWidgets.QAction(MainWindow)
        self.render_sequence.setObjectName("render_sequence")
        self.set_default_stroke_width = QtWidgets.QAction(MainWindow)
        self.set_default_stroke_width.setCheckable(True)
        self.set_default_stroke_width.setObjectName("set_default_stroke_width")
        self.set_default_filler_color = QtWidgets.QAction(MainWindow)
        self.set_default_filler_color.setObjectName("set_default_filler_color")
        self.set_default_stroke_color = QtWidgets.QAction(MainWindow)
        self.set_default_stroke_color.setObjectName("set_default_stroke_color")
        self.set_canvas_width = QtWidgets.QAction(MainWindow)
        self.set_canvas_width.setObjectName("set_canvas_width")
        self.set_canvas_height = QtWidgets.QAction(MainWindow)
        self.set_canvas_height.setObjectName("set_canvas_height")
        self.set_canvas_scale_step = QtWidgets.QAction(MainWindow)
        self.set_canvas_scale_step.setObjectName("set_canvas_scale_step")
        self.play = QtWidgets.QAction(MainWindow)
        self.play.setObjectName("play")
        self.set_ghost = QtWidgets.QAction(MainWindow)
        self.set_ghost.setCheckable(True)
        self.set_ghost.setChecked(True)
        self.set_ghost.setObjectName("set_ghost")
        self.file_window.addAction(self.to_choose_project_window)
        self.render_window.addAction(self.render_animation)
        self.render_window.addAction(self.render_sequence)
        self.render_window.addAction(self.play)
        self.help_window.addAction(self.documentation)
        self.help_window.addAction(self.about)
        self.canvas_window.addAction(self.set_canvas_width)
        self.canvas_window.addAction(self.set_canvas_height)
        self.canvas_window.addAction(self.set_canvas_scale_step)
        self.canvas_window.addAction(self.set_default_stroke_width)
        self.canvas_window.addAction(self.set_default_stroke_color)
        self.canvas_window.addAction(self.set_default_filler_color)
        self.canvas_window.addAction(self.set_ghost)
        self.menubar.addAction(self.file_window.menuAction())
        self.menubar.addAction(self.render_window.menuAction())
        self.menubar.addAction(self.canvas_window.menuAction())
        self.menubar.addAction(self.help_window.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.first_frame.setText(_translate("MainWindow", "На первый кадр"))
        self.label_3.setText(_translate("MainWindow", "Текущий кадр"))
        self.timeline_visual_multiplier_description.setText(_translate("MainWindow", "Размер таймлайна 100%"))
        self.label_2.setText(_translate("MainWindow", "Частота кадров"))
        self.move_to_background.setText(_translate("MainWindow", "Переместить назад"))
        self.move_to_overground.setText(_translate("MainWindow", "Переместить вперед"))
        self.change_object.setText(_translate("MainWindow", "Изменить"))
        self.delete_object.setText(_translate("MainWindow", "Удалить"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.last_frame.setText(_translate("MainWindow", "На последний кадр"))
        self.delete_frame.setText(_translate("MainWindow", "Удалить кадр"))
        self.pencil_tool.setText(_translate("MainWindow", "Ручка"))
        self.line_tool.setText(_translate("MainWindow", "Линия"))
        self.ellipse_tool.setText(_translate("MainWindow", "Окружность"))
        self.fill_tool.setText(_translate("MainWindow", "Заливочный\n"
"контур"))
        self.copy_frame.setText(_translate("MainWindow", "Копировать кадр"))
        self.paste_frame.setText(_translate("MainWindow", "Вставить кадр"))
        self.create_frame.setText(_translate("MainWindow", "Создать кадр"))
        self.previous_frame.setText(_translate("MainWindow", "На кадр назад"))
        self.next_frame.setText(_translate("MainWindow", "На кадр вперед"))
        self.file_window.setTitle(_translate("MainWindow", "Файл"))
        self.render_window.setTitle(_translate("MainWindow", "Рендер"))
        self.help_window.setTitle(_translate("MainWindow", "Помощь"))
        self.canvas_window.setTitle(_translate("MainWindow", "Холст"))
        self.to_choose_project_window.setText(_translate("MainWindow", "Главное меню"))
        self.to_choose_project_window.setShortcut(_translate("MainWindow", "Home"))
        self.render_animation.setText(_translate("MainWindow", "Рендер анимации"))
        self.documentation.setText(_translate("MainWindow", "Документация"))
        self.documentation.setShortcut(_translate("MainWindow", "F1"))
        self.about.setText(_translate("MainWindow", "О программе"))
        self.render_sequence.setText(_translate("MainWindow", "Рендер секвенции"))
        self.set_default_stroke_width.setText(_translate("MainWindow", "Обычная толщина обводки"))
        self.set_default_filler_color.setText(_translate("MainWindow", "Обычный цвет заливки"))
        self.set_default_stroke_color.setText(_translate("MainWindow", "Обычный цвет обводки"))
        self.set_canvas_width.setText(_translate("MainWindow", "Ширина холста"))
        self.set_canvas_height.setText(_translate("MainWindow", "Высота холста"))
        self.set_canvas_scale_step.setText(_translate("MainWindow", "Шаг масштабирования холста"))
        self.play.setText(_translate("MainWindow", "Предпросмотр анимации"))
        self.play.setShortcut(_translate("MainWindow", "Space"))
        self.set_ghost.setText(_translate("MainWindow", "Отображение предыдущего кадра"))
